<?php

// Call userTest::main() if this source file is executed directly.
if ( ! defined( 'PHPUnit_MAIN_METHOD' ) )
{
    define( 'PHPUnit_MAIN_METHOD', 'userTest::main' );
}

require_once 'PHPUnit/Framework.php';

if ( is_file( '../../../include/config_inc.php' ) )
{
    require_once '../../../include/config_inc.php';
}
else 
    if ( is_file( '../include/config_inc.php' ) )
    {
        require_once '../include/config_inc.php';
    }
    else
    {
        require_once 'include/config_inc.php';
    }

require_once TBW_ROOT . 'engine/include.php';
require_once TBW_ROOT . 'engine/classes/galaxy.php';
require_once TBW_ROOT . 'test/TestData/TestConstants.php';
require_once TBW_ROOT . 'test/TestData/TestData.php'; 
require_once TBW_ROOT . 'test/TestData/Tester.php';
require_once TBW_ROOT . 'test/TestData/TestMessage.php';

/**
 * Test class for user.
 * Generated by PHPUnit on 2009-10-31 at 06:39:22.
 */
class userTest extends PHPUnit_Framework_TestCase
{
    private $testData;

    /**
     * tests if all researches within testData exists on the user itself
     * @param User $user
     * @param TestPlanet $planetData
     * @return -
     */
    public function _testActiveResearch( &$user, &$planetData )
    {
        $this->assertTrue( $user->setActivePlanet( $planetData->getIndex() ) );
        
        $research = $planetData->getActiveResearch();
        
        if ( $research == false )
            return;
            //		else
        //			print "testing research...\n";
        

        $aForschung = $user->checkBuildingThing( "forschung" );
        
        $this->assertEquals( $research->getId(), $aForschung[0], "failed comparing research id on planet " . $user->getActivePlanet() . " on user " . $user->getName() . "\n" );
        $this->assertEquals( $research->getGlobal(), $aForschung[2] );
        
        if ( $research->isGlobal() )
        {
            $this->assertEquals( $research->getStartPlanet(), $aForschung[4], "_testActiveResearch() failed for user " . $user->getName() . " planet: " . $user->getActivePlanet() . "\n" );
        }
        else
        {
            $this->assertFalse( isset( $aForschung[4] ) );
        }
    }

    /**
     * tests if users messages equals their messages stored within the testdata
     * @param string $uname
     * @return -
     */
    public function _testMessages( $uname )
    {
        $user = Classes::User( $uname );
        $testUser = $this->testData->getUserWithName( $uname );
        $testMsgs = $testUser->getMessages();
        $i = 0;
        
        foreach ( $testMsgs as $testMsg )
        {
            $found = 0;
            
            foreach ( $user->getMessagesList( $testMsg->getType() ) as $msg )
            {
                $msgObj = Classes::Message( $msg );
                
                if ( $msgObj->rawText() == $testMsg->getText() && $testMsg->getText() != "" )
                {
                    if ( $msgObj->getSubject() == $testMsg->getSubject() && $testMsg->getSubject() != "" )
                    {
                        if ( $msgObj->from( $uname ) == $testMsg->getFrom() )
                        {
                            $found ++;
                        }
                        else
                            echo "from doesnt match\n";
                    }
                    else
                        echo "subject doesnt match\n";
                }
                else
                    echo "test doesnt match - expected: \n" . $testMsg->getText() . "\n == \n" . $msgObj->rawText() . "\n";
            }
            $this->assertEquals( 1, $found );
        }
        $this->greaterThan( 0, $i );
    }

    /*
	 * send a fleet and test if it were created
	 * the actual testing it derivated into a sub method
	 */
    public function _testSendFleetTo( $uname, $pos )
    {
        $fleet = Classes::Fleet();
        $user = Classes::User( $uname );
        $mypos = $user->getPosString();
        unset( $user );
        
        //		echo "\nflying from: ".$mypos. " to: ".$pos."\n";
        

        /*
		 * flotte als transport mit 10 kleinen transportern zum ziel $pos versenden
		 */
        $type = 6; // stationieren
        $fleet->create(); // no return 
        $this->test_Fleets[$uname][] = $fleet->getName();
        $this->assertTrue( $fleet->addTarget( $pos, $type, false ) );
        $this->assertEquals( $uname, $fleet->addUser( $uname, $mypos, 1 /* default */ ) );
        $this->assertTrue( $fleet->addTransport( $uname, array( 0, 0, 0, 0, 0 ), array() ) );
        $this->assertTrue( $fleet->addFleet( "S1", 100, $uname ) );
        $this->assertTrue( $fleet->addHoldTime( 0 ) );
        $this->assertGreaterThan( 0, $fleet->calcNeededTritium( $uname ) );
        $fleet->start(); // no return
        $this->assertEquals( $pos, $fleet->getCurrentTarget() );
        
        $user = Classes::User( $uname );
        $this->assertTrue( $user->addFleet( $fleet->getName() ) );
        unset( $user );
        unset( $fleet );
        
        $this->_testIsFleetExistingSpecific( $uname, $pos, $mypos, array( "S1", 10 ), $type, false );
    }

    /**
     * returns the MAX_PLANETS global setting and tests it for plausibility
     * @return unknown_type
     */
    public function _testAndGetMaxPlanets( )
    {
        $maxplanets = global_setting( "MAX_PLANETS" );
        
        $this->assertGreaterThan( 1, $maxplanets );
        
        return $maxplanets;
    }

    /**
     * gets rid of old data stored in database for a fresh test setup
     * @param string $dir
     * @return -
     */
    protected function _tearDown_DeleteDir( $dir )
    {
        $exclude = array( '.', '..' );
        $files = array_diff( scandir( $dir ), $exclude );
        
        foreach ( $files as $value )
        {
            $fname = $dir . "/" . $value;
            
            if ( ! is_dir( $fname ) && is_file( $fname ) && is_writable( $fname ) )
            {
                unlink( $fname );
            }
        }
    }

    /**
     * subfunc for testing the whole setup
     * @param TestUser $userData
     * @return -
     */
    public function _testSetup( &$userData )
    {
        if ( $userData->shouldCreate() && $userData->shouldCreateOnSetup() )
        {
            $this->assertTrue( User::userExists( $userData->getName() ) );
        }
        else
        {
            $this->assertFalse( User::userExists( $userData->getName() ), "user " . $userData->getName() . " exists but shouldnt" );
        }
        
        if ( ! $userData->isCreated() )
        {
            $this->assertFalse( User::userExists( $userData->getName() ) );
            return;
        }
        
        $this->_testScoresOfUser( $userData );
        $userObj = Classes::User( $userData->getName() );
        
        foreach ( $userData->getPlanets() as $planetData )
        {
            $i = $planetData->getIndex();
            
            if ( $planetData->isCreated() )
            {
                $this->assertTrue( $userObj->setActivePlanet( $i ) );
                $this->assertTrue( $userObj->planetExists( $i ) );
                $this->assertEquals( $planetData->getName(), $userObj->planetName(), "for index: " . $i . "\n" );
                $this->_testPlanetItems( $userObj, $planetData );
                $this->_testRes( $userObj, $planetData );
            }
            else
            {
                $this->assertFalse( $userObj->setActivePlanet( $i ) );
                $this->assertFalse( $userObj->planetExists( $i ) );
                //$this->assertFalse( $userObj->planetName() ); // doesnt work, cause we couldnt change to that planet with setActivePlanet()
            }
        }
        
        //$userObj->doRecalcHighscores( true, true, true, true, true );
    }

    /**
     * 
     * @param $userData
     * @return unknown_type
     */
    private function _testScoresOfUser( &$userData )
    {
        $testScores = &$userData->getScores();
        $userObj = Classes::User( $userData->getName() );
        $this->assertType( 'object', $userObj );
        
        $userObj->doRecalcHighscores( true, true, true, true, true );
        $userObj->clearCache();
        
        $testPlanets = $userData->getPlanets();
        
        foreach ( $testPlanets as $testPlanet )
        {
            $ret = $userObj->setActivePlanet( $testPlanet->getIndex() );
            
            if ( $ret === false )
            {
                $this->assertFalse( $testPlanet->isCreated() );
                continue;
            }
            else
                $this->assertTrue( $testPlanet->isCreated() );
            
            $testItems = $testPlanet->getItems();
            
            // check all buildings
            $items = $userObj->getItemsList( 'gebaeude' );
            
            foreach ( $items as $item )
            {
                // test if item exists in our test data
                $this->assertTrue( isset( $testItems[$item] ), "item: " . $item . " on planet: " . $testPlanet->getIndex() . " of user: " . $userData->getName() . " doesnt exists in testData" );
                
                $this->assertEquals( $testPlanet->getIndex(), $userObj->getActivePlanet() );
                
                $testItem = $testItems[$item];
                $item_info = $userObj->getItemInfo( $item, 'gebaeude', true, true );
                
                // test if score of the item is the same as in our test data
                $this->assertEquals( $item_info['scores'], $testItem->getScore(), "failed comparing score for " . $item . " user: " . $userObj->getName() . " planet: " . $testPlanet->getIndex() . " level of testItem: " . $testItem->getLevel() . " level of realItem: " . $item_info['level'] );
            }
            
            // check all robots
            $items = $userObj->getItemsList( 'roboter' );
            
            foreach ( $items as $item )
            {
                // test if item exists in our test data
                $this->assertTrue( isset( $testItems[$item] ), "item: " . $item . " on planet: " . $testPlanet->getIndex() . " of user: " . $userData->getName() . " doesnt exists in testData" );
                
                $testItem = $testItems[$item];
                $item_info = $userObj->getItemInfo( $item, 'roboter', true, true );
                
                // test if score of the item is the same as in our test data
                $this->assertEquals( $item_info['scores'], $testItem->getScore(), "failed comparing score for " . $item . " user: " . $userObj->getName() . " planet: " . $testPlanet->getIndex() );
            }
            
            // check all ships
            $items = $userObj->getItemsList( 'schiffe' );
            
            foreach ( $items as $item )
            {
                // test if item exists in our test data
                $this->assertTrue( isset( $testItems[$item] ), "item: " . $item . " on planet: " . $testPlanet->getIndex() . " of user: " . $userData->getName() . " doesnt exists in testData" );
                
                $testItem = $testItems[$item];
                $item_info = $userObj->getItemInfo( $item, 'schiffe', true, true );
                
                // test if score of the item is the same as in our test data
                $this->assertEquals( $item_info['scores'], $testItem->getScore(), "failed comparing score for " . $item . " user: " . $userObj->getName() . " planet: " . $testPlanet->getIndex() );
            }
            
            // check all defense
            $items = $userObj->getItemsList( 'verteidigung' );
            
            foreach ( $items as $item )
            {
                // test if item exists in our test data
                $this->assertTrue( isset( $testItems[$item] ), "item: " . $item . " on planet: " . $testPlanet->getIndex() . " of user: " . $userData->getName() . " doesnt exists in testData" );
                
                $testItem = $testItems[$item];
                $item_info = $userObj->getItemInfo( $item, 'verteidigung', true, true );
                
                // test if score of the item is the same as in our test data
                $this->assertEquals( $item_info['scores'], $testItem->getScore(), "failed comparing score for " . $item . " user: " . $userObj->getName() . " planet: " . $testPlanet->getIndex() );
            }
        }
        
        $k = 0;
        
        // till 11 or more for ressource scores - but should be 11
        for ( $i = 0; $userObj->getScores( $i ) != 0 || $i <= 11; $i ++ )
        {
            if ( $i == 1 )
            {
                continue;
            }
            
            $sum = 0;
            
            //$userObj->doRecalcHighscores( true, true, true, true, true, true );
            if ( $i >= 0 && $i <= 4 )
                $sum = $userData->getSumScores( $i );
            else 
                if ( $i >= 4 && $i <= 11 )
                {
                    $testScores = $userData->getScores();
                    $sum = $testScores->getScoreID( $i );
                }
            
            $this->assertGreaterThanOrEqual( 0, $sum );
            $diff = $sum - $userObj->getScores( $i );
            $this->assertEquals( $sum, $userObj->getScores( $i ), "_testScoresOfUser() failed, for key: " . $i . " diff: " . $diff . "\n" );
            
            $k ++;
        }
        
        // we expect to test 11 score values
        $this->assertEquals( 11, $k );
        
        $sum = 0;
        $testScoresArray = $testScores->getAllScoresAsArray();
        
        for ( $i = 0; $i <= 6; $i ++ )
        {
            $sum += $testScoresArray[$i];
            //print "testScoresArray() adding " . $testScoresArray[$i] . " for id: " . $i . " user: " . $userData->getName() . "\n";
        }
        
        $userObj->doRecalcHighscores( true, true, true, true, true );
        $userObj->clearCache();
        
        $this->assertGreaterThan( 0, $sum, "testscores of user " . $userData->getName() . " are empty?!\n" );       

        // scores only exists up to 11, above shouldnt exists
        $this->assertEquals( 0, $userObj->getScores( 12 ) );
        
        // erase cache and retest
        $userObj->doRecalcHighscores( true, true, true, true, true );
    }

    /*
	 * test if a given fleet is existant, it is expected to do, otherwise this test will fail
	 */
    public function _testIsFleetExistingSpecific( $from_user, $to_pos, $from_pos, $ships, $type, $flyingback )
    {
        $user = Classes::User( $from_user );
        $fleets = $user->getFleetsList();
        
        $this->assertGreaterThan( 0, count( $fleets ), "no fleets found" );
        
        $fleet = false;
        
        foreach ( $fleets as $ffleet )
        {
            $fleet = $ffleet;
        }
        
        if ( $fleet == false )
            throw new Exception( "_testIsFleetExistingSpecific() failed, no fleet found" );
        
        $fleet_obj = Classes::Fleet( $fleet );
        $that = Classes::Fleet( $fleet );
        $blub = $user->getFleetsWithPlanet();
        
        unset( $user );
        
        $targets = $that->getTargetsList();
        
        $this->assertEquals( array( $to_pos ), $targets );
        $this->assertEquals( array( "S1" => 100 ), $fleet_obj->getFleetList( $from_user ) );
        
        if ( ! $flyingback )
        {
            $this->assertFalse( $fleet_obj->isFlyingBack() );
        }
        else
        {
            $this->assertTrue( $fleet_obj->isFlyingBack() );
        }
    }

    /**
     * compares all planet items stored in testdata to the actual existing ones on the users planet
     * @param User $user
     * @param TestPlanet $planetData
     * @return -
     */
    public function _testPlanetItems( &$user, &$planetData )
    {
        $this->assertGreaterThanOrEqual( 0, $planetData->getIndex() );
        
        $this->assertTrue( $user->setActivePlanet( $planetData->getIndex() ) );
        
        foreach ( $planetData->getItems() as $itemData )
        {
            $id = $itemData->getId();
            $level = $itemData->getLevel();
            
            $lvl = $user->getItemLevel( $id, false, false );
            if ( $level != $lvl /*&& $planetData->getIndex() == 4*/)
				echo "MISMATCH -- expected: " . $level . " got: " . $lvl . " for item: " . $id . " on planet " . $planetData->getName() . " (" . $user->planetName() . ")\n";
            $this->assertEquals( $level, $lvl, '_testPlanetItems() expected level didnt match for given item ' . $id . ' wanted: ' . $level . ' got: ' . $lvl );
            //echo "testing item: ".$id." for level: ".$level." which is: ".$lvl."\n";
        }
        
        $this->_testActiveResearch( $user, $planetData );
    }

    /**
     * compares main ressources from testData to the existing ones on the planet
     * @param User $user
     * @param TestPlanet $planetData
     * @return -
     */
    public function _testRes( &$user, &$planetData )
    {
        $this->assertTrue( $user->setActivePlanet( $planetData->getIndex() ) );
        
        $testRes = $planetData->getRes();
        $planetRes = $user->getRess();
        
        foreach ( $testRes as $key => $value )
        {
            // TODO, check and calc tritium
            if ( $key == 4 )
            {
                continue;
            }
            
            // TODO, needs more accurate check
            $this->assertGreaterThanOrEqual( $testRes[$key], $planetRes[$key], $key . " didnt match of planet " . $planetData->getIndex() . " - " . $planetData->getName() . " of user " . $user->getName() . "\n" );
        }
    
    }

    protected function _buildTestHighScore()
    {
        $userObj = NULL;
        
        foreach ( $this->testData->getTestUsers() as $testUser )
        {
            if ( ! $testUser->isCreated() )
            {
                $userObj = Classes::User( $testUser->getName() );
                continue;
            }
            else
            {
                $userObj = Classes::User( $testUser->getName() );
            }

            $userObj->doRecalcHighscores( true, true, true, true, true );
            $testHighScore = &$this->testData->getTestHighscore();
            $testHighScore->addUser( $userObj->getName(), $userObj->getScores() );
        }        
        
        $testHighScore->buildRankList();
    }       
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp( )
    {
        // must be the FIRST line   	
        // define_globals( Uni ); to set globals like where db files are located etc
        define_globals( 'TestUni1' );
        
        $this->cleanUp();
        
        $this->testData = new TestData( );
        $this->tester = new Tester( $this->testData );
        $this->tester->setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown( )
    {

    }

    protected function cleanUp( )
    {
        
        Classes::resetInstances();
        /*
		foreach( $this->testData->getTestUsers() as $user )
		{
			user_control::removeUser( $user->getName() );
		}

		Classes::resetInstances();
		*/
        
        $this->_tearDown_DeleteDir( global_setting( "DB_PLAYERS" ) );
        $this->_tearDown_DeleteDir( global_setting( "DB_FLEETS" ) );
        $this->_tearDown_DeleteDir( global_setting( "DB_MESSAGES" ) );
    }
    
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main( )
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';
        
    //$suite  = new PHPUnit_Framework_TestSuite('userDevTest');
    //$result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////// TESTS START HERE //////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    

    /**
     * test our test setup
     */
    public function testSetup( )
    {
        foreach ( $this->testData->getTestUsers() as $userData )
        {
            $this->_testSetup( $userData );
        }
    }

    /**
     * check new user creation
     */
    public function testCreate( )
    {
        $usa = $this->testData->getUnusedUser();
        
        if ( $usa === false )
        {
            throw new Exception( "testCreate() failed, no remaining users for testing" );
        }
        
        // new user
        $newuser = Classes::User( $usa->getName() );
        
        // already exists
        $dupuser = Classes::User( $usa->getName() );
        
        $this->assertTrue( $newuser->create(), "couldnt create user" );
        
        $usa->setIsCreated( true );
        
        $this->assertFalse( $dupuser->create(), "could create user which already exist" );
    }

    public function testUserExists( )
    {
        foreach ( $this->testData->getTestUsers() as $user )
        {
            if ( $user->isCreated() )
            {
                $this->assertTrue( User::userExists( $user->getName() ), "user which was created doesnt exist" );
            }
            else 
                if ( ! $user->isCreated() )
                {
                    $this->assertFalse( User::userExists( $user->getName() ), "user which wasnt created does exist" );
                }
        }
        
        $this->assertFalse( User::userExists( NULL ), "func returned true but no name was given as parameter" );
    }

    public function testPlanetExists( )
    {
        $users = $this->testData->getTestUsers();
        
        foreach ( $users as $user )
        {
            if ( ! $user->isCreated() )
            {
                continue;
            }
            else
            {
                $userObj = Classes::User( $user->getName() );
                $planets = $user->getPlanets();
                
                foreach ( $planets as $planet )
                {
                    if ( $planet->isCreated() )
                    {
                        $this->assertTrue( $userObj->planetExists( $planet->getIndex() ), "planet setup but doesnt exist" );
                    }
                    else
                    {
                        $this->assertFalse( $userObj->planetExists( $planet->getIndex() ), "planet shouldnt exist" );
                    }
                }
            }
        }
        
        // call it with an initialised user but which doesnt exists
        $fuser = Classes::User( "fakeuser1337" );
        
        for ( $i = 0; $i <= $this->_testAndGetMaxPlanets(); $i ++ )
        {
            $this->assertFalse( $fuser->planetExists( $i ), "planet shouldnt exists on non-existing user" );
        }
    }

    public function testSetActivePlanet( )
    {
        $users = $this->testData->getTestUsers();
        
        foreach ( $users as $user )
        {
            if ( ! $user->isCreated() )
            {
                continue;
            }
            else
            {
                $userObj = Classes::User( $user->getName() );
                $planets = $user->getPlanets();
                
                foreach ( $planets as $planet )
                {
                    if ( $planet->isCreated() )
                    {
                        $this->assertTrue( $userObj->setActivePlanet( $planet->getIndex() ), "planet setup but doesnt exist" );
                    }
                    else
                    {
                        $this->assertFalse( $userObj->setActivePlanet( $planet->getIndex() ), "planet shouldnt exist" );
                    }
                }
            }
        }
        
        // call it with an initialised user but which doesnt exists
        $fuser = Classes::User( "fakeuser1337" );
        
        for ( $i = 0; $i <= $this->_testAndGetMaxPlanets(); $i ++ )
        {
            $this->assertFalse( $fuser->setActivePlanet( $i ), "planet shouldnt exists on non-existing user" );
        }
    }

    public function testGetPlanetByPos( )
    {
        $users = $this->testData->getTestUsers();
        
        // get our very fist user for testing
        $uname = $users[0]->getName();
        $user = Classes::User( $uname );
        
        $fuser = Classes::User( "fakeuser1339" );
        
        $this->assertFalse( $fuser->getPlanetByPos( false ) );
        
        for ( $i = 0; $i <= TEST_MAX_GALAXIES; $i ++ )
        {
            for ( $k = 0; $k <= TEST_MAX_SYSTEMSINGALAXY; $k ++ )
            {
                for ( $m = 0; $m <= TEST_MAX_PLANETSINSYSTEM; $m ++ )
                {
                    if ( rand( 0, 10 ) != 5 )
                    {
                        continue;
                    }
                    
                    $pos = $i . ":" . $k . ":" . $m;
                    $bMyPlanet = false;
                    
                    foreach ( $users[0]->getPlanets() as $planet )
                    {
                        if ( $planet->isCreated() && $pos == $planet->getPosString() )
                        {
                            $bMyPlanet = true;
                            $this->assertEquals( $planet->getIndex(), $user->getPlanetByPos( $pos ) );
                            //echo "found mah planet @ ".$pos."\n"; 
                        }
                    }
                    
                    if ( ! $bMyPlanet )
                        $this->assertFalse( $user->getPlanetByPos( $pos ) );
                }
            }
        }
    }

    /*
	 * checking if the returned planetlist is the same as our one of the created planets
	 */
    public function testGetPlanetsList( )
    {
        $testUsers = $this->testData->getTestUsers();
        $testusr = $testUsers[0];
        
        // get our very fist user for testing
        $user = Classes::User( $testusr->getName() );
        
        $fuser = Classes::User( "fakeuser1340" );
        
        $this->assertFalse( $fuser->getPlanetsList() );
        
        $planets = $user->getPlanetsList();
        
        for ( $i = 0; isset( $planets[$i] ) || $testusr->hasCreatedPlanetAtIndex( $i ); $i ++ )
        {
            $this->assertTrue( isset( $planets[$i] ) );
            $this->assertTrue( $testusr->hasCreatedPlanetAtIndex( $i ) );
        }
    }

    /*
     * checking if the returned planetlist is the same as our one of the created planets
     */
    public function testRemovePlanet( )
    {
        global $types_message_types;
        
        // get our very fist user for the fleet start pos, using active planet
        $testusers = $this->testData->getTestUsers();
        $testUser = $testusers[0];
        $uname = $testUser->getName();
        $user = Classes::User( $uname );
        
        $fuser = Classes::User( "fakeuser1341" );
        
        $this->assertFalse( $fuser->removePlanet() );
        
        /*
		 * fleet zurueckrufen welche zu plani unterwegs ist - testen
		 */
        /*
		$koords = $user->getPosString();
		$i = 0;

		while( $koords == $user->getPosString() && $i < 100 )
		{
			$i++;
			$usr = array_rand( $this->test_PlanetCoordinates );
			$planet = array_rand( $this->test_PlanetCoordinates[$usr] );
			$koords = $this->test_PlanetCoordinates[$usr][$planet];

			$this->assertLessThan( 100, $i );
		}
		*/
        
        // set active planet to 0 and send fleet to planet 1
        $user->setActivePlanet( 0 );
        $planets = $testUser->getPlanets();
        $mypos = $user->getPosString();
        $pos = $planets[1]->getPosString();
        $toName = $planets[1]->getName();
        $fromName = $planets[0]->getName();
        $type = 6; // stationieren
        $delPlanetIndex = 1;
        $delPlanetPos = $mypos;
        
        $this->_testSendFleetTo( $uname, $pos );
        
        // core func, remove the planet
        $user = Classes::User( $uname );
        $this->assertTrue( $user->setActivePlanet( $delPlanetIndex ) );
        $this->assertTrue( $user->removePlanet() );
        unset( $user );
        
        $fleet_obj = Classes::Fleet( $this->test_Fleets[$uname][0] );
        // check if the fleet was sent back
        $this->_testIsFleetExistingSpecific( $uname, $mypos, $pos, array( "S1", 10 ), $type, true );
        
        // check if planet still exists
        $galaxy = Classes::Galaxy( 1 );
        $koords = explode( ":", $pos );
        $this->assertEquals( "", $galaxy->getPlanetOwner( $koords[1], $koords[2] ) );
        
        $user = Classes::User( $uname );
        $msgs = $user->getMessagesList( 3 );
        $msg = Classes::Message( $msgs[0] );
        
        //echo $msg->rawText()."\n";
        

        $testMsg = new TestMessage( );
        $testMsg->setSubject( 'Flotte zur&uuml;ckgerufen' );
        $testMsg->setText( 'Ihre Flotte befand sich auf dem Weg zum Planeten &bdquo;' . $toName . '&ldquo; (' . $pos . ', Eigent&uuml;mer: ' . $user->getName() . '). Soeben wurde jener Planet verlassen, weshalb Ihre Flotte sich auf den R&uuml;ckweg zu Ihrem Planeten &bdquo;' . $fromName . '&ldquo; (' . $mypos . ') macht.' );
        $testMsg->setFrom( $uname );
        $testMsg->setType( $types_message_types[$type] );
        $testUser->addMessage( $testMsg );
        
        $this->_testMessages( $uname );
        
        // check if we still have a link to the old planet
        foreach ( $user->getPlanetsList() as $planet )
        {
            $this->assertTrue( $user->setActivePlanet( $planet ) );
            $this->assertNotSame( $delPlanetPos, $user->getPos() );
        }
        
    //maybe TODO, highscores test, something happens with research
    }

    public function testRegisterPlanet( )
    {
        $fuser = Classes::User( "fakeuser1341" );
        $freeKoords = getFreeKoords();
        $maxplanets = $this->_testAndGetMaxPlanets();
        $testUsers = $this->testData->getTestUsers();
        $testUser = $testUsers[0];
        $user = Classes::User( $testUser->getName() );
        $loops = 0;
        
        while ( $testUser->getCreatedPlanetCount() <= $maxplanets + 1 )
        {
            $loops ++;
            $this->assertLessThan( 100, $loops );
            
            if ( $freeKoords == false )
            {
                throw new Exception( "testRegisterPlanet() failed, no free coords available" );
            }
            
            $testCount = $testUser->getCreatedPlanetCount();
            
            if ( $testCount >= $maxplanets )
            {
                $index = $user->registerPlanet( $freeKoords );
                $this->assertFalse( $index );
                break;
            }
            else
            {
                $index = $user->registerPlanet( $freeKoords );
                $this->assertGreaterThanOrEqual( 0, $index, 'registerPlanet() failed, current planetcount is :' . $testUser->getPlanetCount() );
                $testUser->addNewPlanetCreated( $index, $freeKoords );
            }
            
            $freeKoords = getFreeKoords();
        }
        
        // non-existant galaxy - 9
        $this->assertFalse( $user->registerPlanet( "9:" . $freeKoords[1] . ":" . $freeKoords[2] ) );
        
        // malformed koordinates
        $this->assertFalse( $fuser->registerPlanet( "1:3:3:7" ) );
        
        $testPlanets = $testUser->getPlanets();
        $testPlanet = NULL;
        
        // try to register an already existing planet
        foreach ( $testPlanets as $planet )
        {
            if ( $planet->isCreated() )
            {
                $testPlanet = &$planet;
            }
        }
        
        $this->assertNotNull( $testPlanet );
        $this->assertFalse( $user->registerPlanet( $testPlanet->getGalaxy() . ":" . $testPlanet->getSystem() . ":" . $testPlanet->getSysIndex() ) );
        
        // 1st registered planet always has 375 fields
        $freeKoords = getFreeKoords();
        $freeKoordsArray = explode( ":", $freeKoords );
        $newTestUser = $this->testData->getUnusedUser();
        $usaName = $newTestUser->getName();
        $newUser = Classes::User( $usaName );
        $newUser->create();
        $newTestUser->setIsCreated( true );
        $index = $newUser->registerPlanet( $freeKoords );
        $testPlanet = $newTestUser->addNewPlanetCreated( $index, $freeKoords );
        $this->assertGreaterThanOrEqual( 0, $index );
        $newUser->setActivePlanet( $index );
        
        $galaxy = Classes::Galaxy( $freeKoords[0] );
        $this->assertGreaterThan( 0, $galaxy->getStatus() );
        $this->assertEquals( 375, $newUser->getBasicFields() );
        // we cant compare this, since galaxys size doesnt get overwritten when creating a 1st planet	
        //$this->assertEquals(375, $galaxy->getPlanetSize($freeKoordsArray[1], $freeKoordsArray[2]));
        

        // default planet name is "Kolonie"
        $this->assertEquals( "Kolonie", $galaxy->getPlanetName( $freeKoordsArray[1], $freeKoordsArray[2] ) );
        
        // check if research for making planets bigger is applied as it should
        $expFields = $newUser->getBasicFields();
        $newUser->changeItemLevel( "F9", 10, "forschung" );
        $expFields *= $newUser->getItemLevel( 'F9', 'forschung' ) + 1;
        $this->assertEquals( $expFields, $newUser->getFields() );
        $this->assertNotEquals( $expFields, $newUser->getBasicFields() );
        
        // 2nd planet, check if its size is same as galaxy says
        $freeKoords = getFreeKoords();
        $freeKoordsArray = explode( ":", $freeKoords );
        $index = $newUser->registerPlanet( $freeKoords );
        $testPlanet = $newTestUser->addNewPlanetCreated( $index, $freeKoords );
        $this->assertEquals( 1, $index );
        $newUser->setActivePlanet( $index );
        $galaxy = Classes::Galaxy( $freeKoords[0] );
        $this->assertGreaterThan( 0, $galaxy->getStatus() );
        $this->assertGreaterThan( 0, $newUser->getBasicFields() );
        $this->assertGreaterThan( 0, $galaxy->getPlanetSize( $freeKoordsArray[1], $freeKoordsArray[2] ) );
    }

    /**
     * - not existing users cant call that \o/
     * - last planet cant be moved down \o/
     * - all other planets should be able to \o/
     * - check for reassigned researches _o_
     * - check for all items on the planets \o/
     * - check the planetList if they matches the new one \o/
     * - w/o parameter active planet is moved down \o/
     * @return none
     */
    public function testMovePlanetDown( )
    {
        $fuser = Classes::User( "fakeuser1341" );
        $this->assertFalse( $fuser->movePlanetDown( 0 ) );
        $testUsers = $this->testData->getTestUsers();
        
        $testedUsers = 0;
        
        foreach ( $testUsers as &$testUser )
        {
            if ( ! $testUser->isCreated() )
                continue;
            
            $tUser = Classes::User( $testUser->getName() );
            
            $planets = $tUser->getPlanetsList();
            
            $lastPlanetIndex = count( $planets ) - 1;
            
            if ( $lastPlanetIndex == 0 )
            {
                continue;
            }
            
            $this->assertFalse( $tUser->movePlanetDown( $lastPlanetIndex ) );
            
            $planetIndex = array_rand( $planets, 1 );
            
            if ( $planetIndex == $lastPlanetIndex )
            {
                $planetIndex = $lastPlanetIndex - 1;
            }
            $this->testSetup();
            
            $this->assertTrue( $tUser->movePlanetDown( $planetIndex ) );
            
            $testUser->cyclePlanets( $planetIndex, $planetIndex + 1 );
            $this->testSetup();
            
            $this->assertTrue( $tUser->setActivePlanet( $planetIndex ) );
            $this->assertTrue( $tUser->movePlanetdown() );
            $testUser->cyclePlanets( $planetIndex, $planetIndex + 1 );
            $this->testSetup();
            
            $testedUsers ++;
        }
        
        $this->assertGreaterThan( 0, $testedUsers );
    }

    /**
     * - not existing users cant call that \o/
     * - first planet cant be moved up \o/
     * - all other planets should be able to \o/
     * - check for reassigned researches \o_
     * - check for all items on the planets \o/
     * - check the planetList if they matches the new one \o/
     * - w/o parameter active planet is moved up \o/
     * @return none
     */
    public function testMovePlanetUp( )
    {
        $fuser = Classes::User( "fakeuser1342" );
        $this->assertFalse( $fuser->movePlanetUp( 0 ) );
        $testUsers = $this->testData->getTestUsers();
        
        $testedUsers = 0;
        
        foreach ( $testUsers as &$testUser )
        {
            if ( ! $testUser->isCreated() )
                continue;
            
            $tUser = Classes::User( $testUser->getName() );
            
            $planets = $tUser->getPlanetsList();
            
            // this user has no planets, skip
            if ( $planets === false || count( $planets ) == 0 )
            {
                continue;
            }
            
            $this->assertType( 'array', $planets );
            
            // 1st planet cant be moved up
            $this->assertFalse( $tUser->movePlanetUp( 0 ) );
            
            $planetIndex = array_rand( $planets, 1 );
            
            if ( $planetIndex == 0 )
            {
                $planetIndex ++;
            }
            $this->testSetup();
            $this->assertTrue( $tUser->movePlanetUp( $planetIndex ) );
            
            $testUser->cyclePlanets( $planetIndex, $planetIndex - 1 );
            $this->testSetup();
            
            $this->assertTrue( $tUser->setActivePlanet( $planetIndex ) );
            $this->assertTrue( $tUser->movePlanetUp() );
            $testUser->cyclePlanets( $planetIndex, $planetIndex - 1 );
            $this->testSetup();
            
            $testedUsers ++;
        }
        
        $this->assertGreaterThan( 0, $testedUsers );
    }

    /**
     * testing for adding scores via User::addScores()
     * @return none
     */
    public function testAddScores( )
    {
        $userObj = NULL;
        
        foreach ( $this->testData->getTestUsers() as $testUser )
        {
            if ( ! $testUser->isCreated() )
            {
                $userObj = Classes::User( $testUser->getName() );
                $this->assertFalse( $userObj->addScores( 0, 0 ) );
                continue;
            }
            else
            {
                $userObj = Classes::User( $testUser->getName() );
            }
            
            $testScore = &$testUser->getScores();
            
            for ( $i = 0; $i < 20; $i ++ )
            {
                $rScore = rand( 0, 1000 );
                
                if ( $i >= 5 && $i <= 11 )
                {
                    $testScore->addScoreID( $i, $rScore );
                    $this->assertTrue( $userObj->addScores( $i, $rScore ) );
                }
                else 
                    if ( $i >= 0 && $i <= 4 )
                    {
                        // adding score for 0-4 should get erased on the recalculation
                        $this->assertTrue( $userObj->addScores( $i, $rScore ) );
                    }
                    else
                    {
                        $this->assertFalse( $userObj->addScores( $i, $rScore ) );
                    }
            
            }
            
            // do a test of all userScores, testing via User::getScore()
            $this->_testScoresOfUser( $testUser );
        }
    }
    
    /**
     * testing for retrieving spent res via User::getSpentRess()
     * @return none
     */
    public function testGetSpentRess( )
    {
        $userObj = NULL;
        $testCount = 0;
        
        foreach ( $this->testData->getTestUsers() as $testUser )
        {
            if ( ! $testUser->isCreated() )
            {
                $userObj = Classes::User( $testUser->getName() );
                $this->assertFalse( $userObj->getSpentRess( 0 ) );
                continue;
            }
            else
            {
                $userObj = Classes::User( $testUser->getName() );
            }
            
            $testScore = $testUser->getScores();
            $sum = 0;
            
            for ( $i = 0; $i <= 4; $i ++ )
            {
                $sum += $testScore->getScoreID( $i + 7 );                
                $this->assertEquals( $userObj->getSpentRess( $i ), $testScore->getScoreID( $i + 7 ) );                          
            }
            
            $this->assertGreaterThan( 0, $sum );
            $this->assertEquals( $userObj->getSpentRess(), $sum );
                        
            $testCount++;
        }
        
        $this->assertGreaterThan( 0, $testCount );
    }

    /**
     * testing for retrieving users rank in the highscore via User::getRank()
     * - rank is above 0 \o/
     * - rank is correct \o/
     * @return none
     */
    public function testGetRank( )
    {
        $userObj = NULL;
        $this->_buildTestHighScore();
        $testHighScore = $this->testData->getTestHighscore();
        
        foreach ( $this->testData->getTestUsers() as $testUser )
        {
            if ( ! $testUser->isCreated() )
            {
                $userObj = Classes::User( $testUser->getName() );
                continue;
            }
            else
            {
                $userObj = Classes::User( $testUser->getName() );
            }
            
            $ranks = $testHighScore->getRankList(); 
                    
            // check if our user if on the position he says he is
            $userObj->doRecalcHighscores( true, true, true, true, true );
            $this->assertTrue( isset( $ranks[$userObj->getRank()] ), "key: ".$userObj->getRank()." not set user: ".$userObj->getName() );
            $this->assertEquals( $ranks[$userObj->getRank()], $userObj->getName(), "user: ".$userObj->getName()." said he got rank: ".$userObj->getRank()." this rank is used by ".$ranks[$userObj->getRank()]." (testHighscore)\n" );                                   
            $this->assertGreaterThan( 0, $userObj->getRank() );
        }
    }    
    
    /**
	 * most of the User::getScores() is covered by the setupTest, however we need to fill some gaps in coverage
     */
    public function testGetScores( )
    {       
        foreach ( $this->testData->getTestUsers() as $testUser )
        {
            if ( ! $testUser->isCreated() )
            {
                $userObj = Classes::User( $testUser->getName() );
                $this->assertFalse( $userObj->getScores() );
            } 
        }
    }    
    
    /**
     * subtests:
     * - setting illegal planet names \o/
     * - setting legal planet name \o/
     * - getting planet names and compare them to testdata \o/
     * - getting planet names and compare them to previous set \o/ 
     * - test galaxy kram \o/
     */
    public function testPlanetName( )
    {   
        $tested = 0;
            
        foreach ( $this->testData->getTestUsers() as $testUser )
        {
            if ( ! $testUser->isCreated() )
            {
                $userObj = Classes::User( $testUser->getName() );
                $this->assertFalse( $userObj->planetName() );
                
                continue;
            } 
            else
            {
                $userObj = Classes::User( $testUser->getName() );
                $this->assertGreaterThan( 0, $userObj->getStatus() );
                
                if ( $testUser->getPlanetCount() <= 0 )
                {
                    return;
                }
            }
                      
            $planets = $userObj->getPlanetsList();
            
            $this->assertType( 'array', $planets, "user: ".$testUser->getName() );
            
            foreach ( $planets as $planet )
            {
                $userObj->setActivePlanet( $planet );            
            
                // comparing planet names with our internal saved ones
                $testPlanets = $testUser->getPlanets();
                $curTestPlanet = false;
                                
                foreach ( $testPlanets as $testPlanet )
                {
                    if ( $testPlanet->getIndex() == $planet )
                    {
                        $curTestPlanet = $testPlanet;
                    }
                }
                
                $this->assertType('object', $curTestPlanet );
                $this->assertGreaterThan( 0, strlen( $userObj->planetName() ));                
                $this->assertEquals( $curTestPlanet->getName(), $userObj->planetName() );                
                
                // trying different names, allowed ones and disallowed
                $this->assertFalse( $userObj->planetName( 'invalid_name%&%??!.__aa' ) );
                $this->assertFalse( $userObj->planetName( '\\meh' ) );
                $this->assertFalse( $userObj->planetName( '!!' ) );
                $this->assertTrue( $userObj->planetName( 'holy shit' ) );
                $this->assertTrue( $userObj->planetName( 'IMaCOOLname' ) );
                    
                $pos = $userObj->getPos(); 
                $galaxy = Classes::Galaxy( $pos[0] );
                $this->assertEquals( 'IMaCOOLname', $galaxy->getPlanetName( $pos[1], $pos[2] ) );
                
                $this->assertEquals( 'IMaCOOLname', $userObj->planetName() );          
            }  
            $tested++;          
        }
        
        $this->assertGreaterThan( 0, $tested );
    }    
    
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////// TESTS END HERE //////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
}

// Call userTest::main() if this source file is executed directly.
if ( PHPUnit_MAIN_METHOD == 'userTest::main' )
{
    userTest::main();
}
?>
