<?php
// Call userTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'userTest::main');
}

require_once 'PHPUnit/Framework.php';
require_once '../../include/config_inc.php';
require_once( TBW_ROOT.'engine/include.php' );
require_once( TBW_ROOT.'engine/classes/galaxy.php' );

define( 'TEST_MAX_GALAXIES', 2 );
define( 'TEST_MAX_SYSTEMSINGALAXY', 999 );
define( 'TEST_MAX_PLANETSINSYSTEM', 50 );

/**
 * Test class for user.
 * Generated by PHPUnit on 2009-10-31 at 06:39:22.
 */
class userTest extends PHPUnit_Framework_TestCase
{
	private $testUname1 = 'helmut';
	private $testUname2 = 'bernd';
	private $testUname3 = 'olaf';
	private $testCreateUname = 'hans';
	private $testNoUname = 'randomusernotcreatedbefore';

	// used during development, skip tests which are working
	private $skipOldTests = true;

	/*
	 * keeps the random item levels which were set to make sure they were set
	 * array( user, array ( planet, array( itemID, itemLevel ) ) )
	 */
	private $random_ItemLevels = array();

	/*
	 * this holds planets which we created, values = boolean
	 * array( user, array( planetid, bWasCreated ) )
	 */
	private $test_PlanetCreated = array();

	/*
	 * this holds the names of our planets, values = string
	 * array( user, array( planetid, name ) )	
	 */
	private $test_PlanetNames = array();

	/*
	 * this holds the koordinates of our planets, values = string
	 * @array - user => ( planetid => coords )
	 */
	private $test_PlanetCoordinates = array();

	/*
	 * this holds all users used during testing
	 * array( user, array( userobj, username, wascreated ) )
	 */
	private $test_Users = array();

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('userTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
		// define_globals( Uni ); to set globals like where db files are located etc
		define_globals( 'TestUni1' );
		
		$nuser = new User( $this->testUname1 );
		$nuser->create();

		if ( !$nuser->getStatus() )
			throw new Exception( 'setUp() failed, borken for status for $user obj returned' );

		$this->test_Users[] = array( $nuser,  $this->testUname1, true );

        $nuser = new User( $this->testUname2 );
        $nuser->create();

        if ( !$nuser->getStatus() )
            throw new Exception( 'setUp() failed, borken for status for $user obj returned' );

		$this->test_Users[] = array( $nuser,  $this->testUname2, true );
		
		// $this->test_Users[UserID][UserObject]2
		$this->setUp_NewPlanet( $this->test_Users[0][0], "MainPlanet" );
		$this->setUp_NewPlanet( $this->test_Users[0][0], "TestPlanet1" );

        $this->setUp_NewPlanet( $this->test_Users[1][0], "MainPlanet" );
        $this->setUp_NewPlanet( $this->test_Users[1][0], "TestPlanet1" );

		$this->setUp_RandomizePlanet( $this->test_Users[0][0], 0, true );
		$this->setUp_RandomizePlanet( $this->test_Users[0][0], 1, false );

        $this->setUp_RandomizePlanet( $this->test_Users[1][0], 0, true );
		$this->setUp_RandomizePlanet( $this->test_Users[1][0], 1, false );
    }

	protected function setUp_NewUser( $username )
	{
        $nuser = new User( $username );
        $nuser->create();

        array_push( $this->test_Users, array( $nuser, $username, true ) );
	
	}

	/*
	 * helper func for setting up a random planet,
	 * sets and gets back random item levels for each class
	 */
	protected function setUp_RandomPlanet( &$user, $research = false )
	{
		$random_ItemLevels = array();

		$random_ItemLevels = array_merge( $random_ItemLevels, $this->setUp_RandomItemClass( $user, 'gebaeude' ) );
		$random_ItemLevels = array_merge( $random_ItemLevels, $this->setUp_RandomItemClass( $user, 'roboter' ) );
		$random_ItemLevels = array_merge( $random_ItemLevels, $this->setUp_RandomItemClass( $user, 'schiffe' ) );
		$random_ItemLevels = array_merge( $random_ItemLevels, $this->setUp_RandomItemClass( $user, 'verteidigung' ) );

		if ( $research )
			$random_ItemLevels = array_merge( $random_ItemLevels, $this->setUp_RandomItemClass( $user, 'forschung' ) );

		return $random_ItemLevels;
	}

	/*
	 * setting up random items for a given class on the active planet
	 * @args $class - name the class for which all available items should be randomized
	 * @return - returns a list of the random levels with the id as key
	 */
	protected function setUp_RandomItemClass( $user, $class )
	{
		$minlvl = 0;
		$maxlvl = 0;

		switch( $class )
		{
			case 'gebaeude' :
				$minlvl = 0;
				$maxlvl = 20;
			break;

			case 'roboter' :
				$minlvl = 0;
				$maxlvl = 200;
			break;

			case 'schiffe' :
				$minlvl = 0;
				$maxlvl = 9999;
			break;

			case 'verteidigung' :
				$minlvl = 0;
				$maxlvl = 9999;
			break;

			case 'forschung' :
				$minlvl = 0;
				$maxlvl = 20;
			break;

			default:
				throw new Exception( 'setUp_RandomItemClass() called with unsupported class: '.$class );
			break;
		}

        $randomItemLevels = array();
        $itemList = $user->getItemsList( $class );

		if ( !$itemList )
			throw new Exception( 'setUp_RandomItemClass() couldnt get ItemsList of class: '.$class );

		foreach( $itemList as $item )
		{
			$randomLevel = rand( $minlvl, $maxlvl );
			$randomItemLevels[$item] = $randomLevel;
			$user->changeItemLevel( $item, $randomLevel, $class );
//			echo "added ".$randomLevel." items of ".$item."\n";
		}

		return $randomItemLevels;
	}

	/*
	 * sets up a new planet
	 * @args $name - name of the new planet
	 */
	protected function setUp_NewPlanet( &$user, $name = false )
	{
		if ( !$this->setUp_addPlanet( $user, $name ) )
			throw new Exception( 'setUp_MainPlanet() failed, setUp_addPlanet() returned false' );
	}

	/*
	 * this func will randomize all levels for buildings, research, robots and ships on a given planet
	 * and return its values for asserting
	 *
	 * @args $planet - planet which will be the target
	 * @return array() - array containing the random levels
	 */	
	protected function setUp_RandomizePlanet( &$user, $planet, $research = false )
	{
		if ( !$user->planetExists( $planet ) )
		{
			throw new Exception( 'setUp_RandomizePlanet() called with a non existant planet: '.$planet );
		}

		$user->setActivePlanet( $planet );
//		$this->random_ItemLevels[$user->getName()] = array();
		$this->random_ItemLevels[$user->getName()][$planet] = $this->setUp_RandomPlanet( $user, $research );
	}

	/* 
	 * adds another planet to the user
	 */
	protected function setUp_addPlanet( &$user, $name = false )
	{
        $koords = getFreeKoords();

		if( $user == false )
			throw new Exception( 'setUp_MainPlanet() failed, $user is invalid' );

        if( $koords )
        {
//			print "setUp_addPlanet() trying to register a planet for ".$user->getName()." at ".$koords."\n";
            $index = $user->registerPlanet( $koords );

            if ( $index === false )
                throw new Exception( 'setUp_MainPlanet() failed, couldnt setup planet on given coordinates - '.$koords );
            else
            {
                $user->setActivePlanet( $index );

				if ( $name )
				{
	                $user->planetName( $name );
					$this->test_PlanetNames[$user->getName()][$index] = $name;
				}

				$this->test_PlanetCoordinates[$user->getName()][$index] = $koords;
				$this->test_PlanetCreated[$user->getName()][$index] = true;
		
				return true;
            }
        }
        else
            throw new Exception( 'setUp_MainPlanet() failed, no free coordinates for setting up planet' );		
	}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
		foreach( $this->test_Users as $index => $uarray )
		{
			$user = $uarray[0];
	        $ufname = $user->getFileName();
	        $user->__destruct();
	        unset( $user );

			user_control::removeUser( $uarray[1] );

			if ( User::userExists( $uarray[1] ) )
				if ( is_file( $ufname ) )
					unlink( $ufname );
		}
	}

	/**
	 * test our test setup
	 */
	public function testSetup()
	{
        if ( $this->skipOldTests )
			$this->markTestSkipped();

		foreach( $this->test_Users as $index => $usrarray )
		{
			$this->_testSetup( $usrarray[0] );
		}
	}

	public function _testSetup( $user )
	{
        $this->assertTrue( User::userExists( $this->testUname1 ) );

        for( $i = 0; $i <= $this->_testAndGetMaxPlanets(); $i++ )
        {
            if ( isset( $this->test_PlanetCreated[$user->getName()][$i] ) && $this->test_PlanetCreated[$user->getName()][$i] )
            {
                $this->assertTrue( $user->setActivePlanet( $i ) );
                $this->assertTrue( $user->planetExists( $i ) );
                $this->assertEquals( $this->test_PlanetNames[$user->getName()][$i], $user->planetName() );
                $this->_testPlanetItems( $user, $i );
            }
            else
            {
                $this->assertFalse( $user->setActivePlanet( $i ) );
                $this->assertFalse( $user->planetExists( $i ) );
                //$this->assertFalse( $user->planetName() ); // doesnt work, cause we couldnt change to that planet with setActivePlanet()
            }
        }
	}

	public function _testPlanetItems( $user, $planet = false )
	{
		$this->assertGreaterThanOrEqual( 0, $planet );
		
		$user->setActivePlanet( $planet );
	
		foreach( $this->random_ItemLevels[$user->getName()][$planet] as $key => $value )
		{
			$lvl = $user->getItemLevel( $key, false, false );
			$this->assertEquals( $value, $lvl, '_testPlanetItems() expected level didnt match for given item '.$key.' wanted: '.$value.' got: '.$lvl );
		}
	}

	/**
	 * check new user creation
	 */
	public function	testCreate()
	{
		if ( $this->skipOldTests )
			$this->markTestSkipped();

		// new user
		$newuser = new User( $this->testUname3 );

		// already exists
		$dupuser = new User( $this->testUname1 );

		$this->assertTrue( $newuser->create(), "couldnt create user" );

		$this->test_Users[] = array( $newuser,  $this->testUname3, true );

		$this->assertFalse( $dupuser->create(), "could create user which already exist" );
	}

	public function testUserExists()
	{
		if ( $this->skipOldTests )
			$this->markTestSkipped();

		$this->assertTrue( User::userExists( $this->testUname1 ), "user which was created doesnt exist" );
		$this->assertFalse( User::userExists( $this->testNoUname ), "user which wasnt created does exist" );
		$this->assertFalse( User::userExists( NULL ), "func returned true but no name was given as parameter" );
	}

	public function testPlanetExists()
	{
		if ( $this->skipOldTests )
			$this->markTestSkipped();

		// get our very fist user for testing
		$user = $this->test_Users[0][0]; 

		$this->assertTrue( $user->planetExists( 0 ), "planet setup but doesnt exist" );

		for( $i = 0; $i <= $this->_testAndGetMaxPlanets(); $i++ )
		{
			if ( isset( $this->test_PlanetCreated[$user->getName()][$i] ) && $this->test_PlanetCreated[$user->getName()][$i] )
				$this->assertTrue( $user->planetExists( 0 ), "planet setup but doesnt exist" );
			else
				$this->assertFalse( $user->planetExists( $i ), "planet shouldnt exist" );
		}

		// call it with an initialised user but which doesnt exists
		$fuser = new User( "fakeuser1337" );

		for( $i = 0; $i <= $this->_testAndGetMaxPlanets(); $i++ )
		{
			$this->assertFalse( $fuser->planetExists( $i ), "planet shouldnt exists on non-existing user" );
		}
	}

	public function testSetActivePlanet()
	{
		if ( $this->skipOldTests )
			$this->markTestSkipped();

        // get our very fist user for testing
        $user = $this->test_Users[0][0];

		$fuser = new User( "fakeuser1338" );

		$this->assertTrue( $user->setActivePlanet( 0 ), "setting active planet to existing one should work" );

		for( $i = 0; $i <= $this->_testAndGetMaxPlanets(); $i++ )
		{
			$this->assertFalse( $fuser->setActivePlanet( $i ), "planet shouldnt be setable on non-existant user" );
		}
	}

	public function testGetPlanetByPos()
	{
		if ( $this->skipOldTests )
			$this->markTestSkipped();

        // get our very fist user for testing
        $user = $this->test_Users[0][0];

		$fuser = new User( "fakeuser1339" );

		$this->assertFalse( $fuser->getPlanetByPos( false ) );

		for( $i = 0; $i <= TEST_MAX_GALAXIES; $i++ )
		{
			for( $k = 0; $k <= TEST_MAX_SYSTEMSINGALAXY; $k++ )
			{
				for( $m = 0; $m <= TEST_MAX_PLANETSINSYSTEM; $m++ )
				{
					$pos = $i.":".$k.":".$m;
					$bMyPlanet = false;

					foreach( $this->test_PlanetCreated[$user->getName()] as $planet => $isCreated )
					{
						if ( $pos == $this->test_PlanetCoordinates[$user->getName()][$planet] && $isCreated )
						{
							$bMyPlanet = true;
							$this->assertEquals( $planet, $user->getPlanetByPos( $pos ) );
//							echo "found mah planet @ ".$pos."\n"; 
						}
					}

					if ( !$bMyPlanet )
						$this->assertFalse( $user->getPlanetByPos( $pos ) );
				}
			}
		}
	}

	/*
	 * checking if the returned planetlist is the same as our one of the created planets
	 */
	public function testGetPlanetsList()
	{
        if ( $this->skipOldTests )
			$this->markTestSkipped();

		// get our very fist user for testing
        $user = $this->test_Users[0][0];		

		$fuser = new User( "fakeuser1340" );

		$this->assertFalse( $fuser->getPlanetsList() );

		$planets = $user->getPlanetsList();
	
		for( $i = 0; isset( $planets[$i] ) || isset( $this->test_PlanetCreated[$user->getName()][$i] ); $i++ )
		{
			$this->assertTrue( isset( $planets[$i] ) );
			$this->assertTrue( isset( $this->test_PlanetCreated[$user->getName()][$i] ) );
		}
	}

    /*
     * checking if the returned planetlist is the same as our one of the created planets
     */
    public function testRemovePlanet()
    {
        if ( $this->skipOldTests && 0 )
            $this->markTestSkipped();

        // get our very fist user for the fleet start pos, using active planet
        $user = &$this->test_Users[0][0];

		$fuser = new User( "fakeuser1341" );

		$this->assertFalse( $fuser->removePlanet() );

		/*
		 * fleet zurueckrufen welche zu plani unterwegs ist - testen
		 */
		$koords = $user->getPosString();
		$i = 0;

		while( $koords == $user->getPosString() && $i < 100 )
		{
			$i++;
			$usr = array_rand( $this->test_PlanetCoordinates );
			$planet = array_rand( $this->test_PlanetCoordinates[$usr] );
			$koords = $this->test_PlanetCoordinates[$usr][$planet];

			$this->assertLessThan( 100, $i );
		}

		$this->_testSendFleetTo( $user, $koords );
	}

	/*
	 * send a fleet and test if it were created
	 * the actual testing it derivated into a sub method
	 */
	public function _testSendFleetTo( &$user, $pos )
	{
		echo "flying from: ".$user->getPosString(). " to: ".$pos."\n";

		$fleet = New Fleet();

		/*
		 * flotte als transport mit 10 kleinen transportern zum ziel $pos versenden
		 */
		$fleet->create(); // no return 
		$this->assertTrue( $fleet->addTarget( $pos, 3 /* = Angriff */, false ) );
		$this->assertEquals( $user->getName(), $fleet->addUser( $user->getName(), $user->getPosString(), 1 /* default */ ) );
		$this->assertTrue( $fleet->addFleet( "S15", 510, $user->getName() ) );
		$this->assertTrue( $fleet->addFleet( "S1", 100, $user->getName() ) );

		$this->assertTrue( $fleet->addHoldTime( 0 ) );
		$this->assertGreaterThan( 0, $fleet->calcNeededTritium( $user->getName() ) );
		$this->assertTrue( $user->addFleet( $fleet->getName() ) );
		$fleet->start(); // no return
		$this->assertEquals( $pos, $fleet_obj->getCurrentTarget() );

		$this->_testIsFleetExistingSpecific( $user, $pos, $user->getPosString(), array( "S1", 10 ), 4 );
	}

	/*
	 * test if a given fleet is existant, it is expected to do, otherwise this test will fail
	 */
	public function _testIsFleetExistingSpecific( &$from_user, $to_pos, $from_pos, $ships, $type )
	{
		$fleets = $from_user->getFleetsList();

		$this->assertGreaterThan( 0, count( $fleets ), "no fleets found" );

		$fleet = false;

		foreach( $fleets as $ffleet )
		{
		 	$fleet = $ffleet;
		}
	
		if ( $fleet == false )
			throw new Exception( "_testIsFleetExistingSpecific() failed, no fleet found" );

		$that = new Fleet( $fleet );
		$targets = $that->getTargetsList();
print_r ($fleets);

		$this->assertEquals( array( $to_pos, $type ), $targets[0] );
		$this->assertEquals( array( "S1", 10 ), $fleet->getFleetList( $from_user ) );
	}

	public function _testAndGetMaxPlanets()
	{
		$maxplanets = global_setting( "MAX_PLANETS" );

		$this->assertGreaterThan( 1, $maxplanets );

		return $maxplanets;
	}

}

// Call userTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'userTest::main') 
{
    userTest::main();
}
?>
