#!/usr/bin/php

<?php
	$USE_OB = false;
if(!isset($_SERVER['DOCUMENT_ROOT']) || strlen($_SERVER['DOCUMENT_ROOT']) <= 0)
    $_SERVER['DOCUMENT_ROOT'] = getcwd()."/..";
    
require_once($_SERVER['DOCUMENT_ROOT'].'/include/config_inc.php');
require($_SERVER['DOCUMENT_ROOT'].'/engine/include.php');
		
        if(!isset($_SERVER['argv'][1]))
        {
                fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
                exit(1);
        }
        else
        {
                $databases = get_databases();
                if(!define_globals($_SERVER['argv'][1]))
                {
                        fputs(STDERR, "Unknown database.\n");
                        exit(1);
                }
        }

        $dh = opendir(global_setting("DB_PLAYERS"));
 
	$user = new User('Cozutzutlonel Sheppard');
	
	$user->setActivePlanet(1);
        
	$user->changeItemLevel('R04', '-1', 'roboter');


?>
